// react-version/src/components/Footer.jsx
// src/components/Footer.jsx
export default function Footer() {
  return (
    <footer
      className="w-full py-6  text-center text-gray-500 bg-white mt-10"
      role="contentinfo"
    >
      <p className="text-sm">
        &copy; {new Date().getFullYear()} TixHub • All rights reserved.
      </p>
      <span className="font-semibold">Ridwxnullxh</span>
    </footer>
  );
}

// vue-version/src/components/Footer.vue
<template>
  <footer class="w-full bg-white border-t py-6 mt-12">
    <div class="max-w-[1440px] mx-auto px-4 text-center text-sm text-gray-600">
      © {{ year }} TixHub — Built with Vue
    </div>
  </footer>
</template>

<script setup>
import { ref } from "vue";
const year = new Date().getFullYear();
</script>
